#!/bin/bash

USER_PWD=$(cat "$DB_USER_PWD_FILE")
ROOT_PWD=$(cat "$DB_ROOT_PWD_FILE")

echo "
CREATE DATABASE IF NOT EXISTS $DB_NAME ;
CREATE DATABASE IF NOT EXISTS $GF_DATABASE_NAME ;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$USER_PWD' ;
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$MYSQL_USER'@'%' ;
GRANT ALL PRIVILEGES ON $GF_DATABASE_NAME.* TO '$MYSQL_USER'@'%' ;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$ROOT_PWD' ;
FLUSH PRIVILEGES;" >/etc/mysql/init.sql

mkdir -p /run/mysqld

exec mysqld
